import { readFileSync, writeFileSync, mkdirSync } from "fs"
import { join, dirname } from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

// Read the TTF font file
const fontPath = join(
  __dirname,
  "../node_modules/@tscircuit/alphabet/dist/TscircuitAlphabet.ttf",
)
const fontBuffer = readFileSync(fontPath)

// Convert to base64
const base64Font = fontBuffer.toString("base64")

// Generate the output file content
const outputContent = `// Auto-generated file - do not edit manually
// Generated by scripts/encode-font.ts

export default "${base64Font}"
`

// Ensure the assets directory exists
const outputDir = join(__dirname, "../lib/assets")
mkdirSync(outputDir, { recursive: true })

// Write to output file
const outputPath = join(outputDir, "tscircuit-font.ts")
writeFileSync(outputPath, outputContent)

console.log(`✓ Font encoded and written to ${outputPath}`)
console.log(`  Font size: ${(base64Font.length / 1024).toFixed(2)} KB (base64)`)
console.log(`  Original size: ${(fontBuffer.length / 1024).toFixed(2)} KB`)
